#include "dynamicsplitresolver.h"

#include <QDebug>
#include <QDir>
#include <QFile>
#include <QRegularExpression>
#include <QStandardPaths>
#include <QTextStream>

namespace {
// Runtime config lives under /run rather than a user-writable location —
// this daemon already runs as root (same assumption RouterLinux::createTun
// makes when it shells out via "sudo"), and /run is cleared on reboot,
// which is the right lifetime for a config that's regenerated fresh every
// time dynamic split-tunneling starts anyway.
const QString kConfigDir = QStringLiteral("/run/amnezia-split-tunneling");

// Defensive validation before anything derived from user-controlled input
// (the split-tunneling site list, which the user can edit freely in the UI)
// ends up as an argument to ipset/dnsmasq or inside a generated config file.
// QProcess with an argument list (not a shell string) already rules out
// shell injection, but a domain containing e.g. a newline could still
// corrupt the generated dnsmasq config file by injecting extra directives,
// so we validate independently of how it's used downstream.
bool isPlausibleDomain(const QString &domain) {
    static const QRegularExpression validDomain(
        QStringLiteral("^[a-zA-Z0-9]([a-zA-Z0-9-]{0,62}[a-zA-Z0-9])?"
                       "(\\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,62}[a-zA-Z0-9])?)+$"));
    return validDomain.match(domain).hasMatch();
}

bool isPlausibleIpsetName(const QString &name) {
    // ipset(8) itself allows a fairly wide character set for set names, but
    // we control every caller of this class today, so keep this narrow —
    // widen it later only if a real caller needs to.
    static const QRegularExpression validName(QStringLiteral("^[a-zA-Z0-9_-]{1,31}$"));
    return validName.match(name).hasMatch();
}
}  // namespace

DynamicSplitResolver& DynamicSplitResolver::Instance()
{
    static DynamicSplitResolver instance;
    return instance;
}

DynamicSplitResolver::~DynamicSplitResolver()
{
    stop();
}

bool DynamicSplitResolver::isRunning() const
{
    return m_dnsmasqProcess && m_dnsmasqProcess->state() != QProcess::NotRunning;
}

bool DynamicSplitResolver::createIpset(const QString &name, bool isIpv6)
{
    if (!isPlausibleIpsetName(name)) {
        qDebug().noquote() << "DynamicSplitResolver: refusing implausible ipset name" << name;
        return false;
    }

    // Destroy-then-create rather than "create if missing": if a previous
    // run of this exact daemon crashed without calling stop(), we want a
    // clean set, not stale entries from a previous session's site list.
    // Errors from destroy are expected and ignored when the set simply
    // doesn't exist yet.
    QProcess::execute(QStringLiteral("sudo"),
                      {QStringLiteral("ipset"), QStringLiteral("destroy"), name});

    QStringList createArgs;
    createArgs << QStringLiteral("ipset") << QStringLiteral("create") << name
              << QStringLiteral("hash:ip") << QStringLiteral("family")
              << (isIpv6 ? QStringLiteral("inet6") : QStringLiteral("inet"));

    QProcess process;
    process.start(QStringLiteral("sudo"), createArgs);
    if (!process.waitForStarted(1000) || !process.waitForFinished(2000) ||
        process.exitCode() != 0) {
        qDebug().noquote() << "DynamicSplitResolver: failed to create ipset" << name
                          << process.readAllStandardError();
        return false;
    }

    return true;
}

bool DynamicSplitResolver::destroyIpset(const QString &name)
{
    if (name.isEmpty()) {
        return true;
    }
    // Best-effort: dnsmasq must already be stopped (nothing referencing the
    // set) before this can succeed, which start()/stop() ordering below
    // guarantees. A failure here (e.g. set already gone) isn't fatal to
    // the overall stop() sequence.
    QProcess::execute(QStringLiteral("sudo"),
                      {QStringLiteral("ipset"), QStringLiteral("destroy"), name});
    return true;
}

bool DynamicSplitResolver::writeDnsmasqConfig(
    const QString &path, const QHostAddress &listenAddress, quint16 listenPort,
    const QStringList &splitDomains, const QStringList &upstreamServers,
    const QString &ipsetV4Name, const QString &ipsetV6Name)
{
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
        qDebug().noquote() << "DynamicSplitResolver: cannot write config to" << path;
        return false;
    }

    QTextStream out(&file);

    out << "# Generated by AmneziaVPN dynamic split-tunneling — do not edit by hand,\n";
    out << "# regenerated fresh on every start.\n";
    out << "no-daemon\n";
    out << "no-resolv\n";
    out << "no-hosts\n";
    out << "bind-interfaces\n";
    out << "listen-address=" << listenAddress.toString() << "\n";
    out << "port=" << listenPort << "\n";
    // Drop root once the (possibly <1024) port is bound — same privilege-
    // drop pattern the system dnsmasq.service unit uses.
    out << "user=nobody\n";
    out << "group=nogroup\n";

    for (const QString &server : upstreamServers) {
        out << "server=" << server << "\n";
    }

    QStringList validDomains;
    for (const QString &domain : splitDomains) {
        if (isPlausibleDomain(domain)) {
            validDomains << domain;
        } else {
            qDebug().noquote() << "DynamicSplitResolver: skipping implausible domain"
                              << domain;
        }
    }

    if (!validDomains.isEmpty()) {
        // A single combined directive: dnsmasq's --ipset syntax accepts
        // multiple domains under one rule (/domain1/domain2/.../set,set6),
        // so every A answer for any of these domains goes to ipsetV4Name
        // and every AAAA answer goes to ipsetV6Name, in one line rather
        // than one directive per domain.
        out << "ipset=/" << validDomains.join(QStringLiteral("/")) << "/"
           << ipsetV4Name << "," << ipsetV6Name << "\n";
    }

    file.close();
    return true;
}

bool DynamicSplitResolver::start(const QHostAddress &listenAddress, quint16 listenPort,
                                 const QStringList &splitDomains,
                                 const QStringList &upstreamServers,
                                 const QString &ipsetV4Name, const QString &ipsetV6Name)
{
    // Starting fresh always stops whatever was running before — see class
    // comment, this owns exactly one resolver at a time.
    stop();

    if (splitDomains.isEmpty()) {
        qDebug().noquote() << "DynamicSplitResolver: no split domains given, nothing to do";
        return false;
    }
    if (upstreamServers.isEmpty()) {
        qDebug().noquote() << "DynamicSplitResolver: no upstream DNS servers given, refusing "
                              "to start with nowhere to forward to";
        return false;
    }

    QDir().mkpath(kConfigDir);

    if (!createIpset(ipsetV4Name, false)) {
        return false;
    }
    if (!createIpset(ipsetV6Name, true)) {
        destroyIpset(ipsetV4Name);
        return false;
    }

    const QString configPath = kConfigDir + QStringLiteral("/dnsmasq.conf");
    if (!writeDnsmasqConfig(configPath, listenAddress, listenPort, splitDomains,
                            upstreamServers, ipsetV4Name, ipsetV6Name)) {
        destroyIpset(ipsetV4Name);
        destroyIpset(ipsetV6Name);
        return false;
    }

    m_dnsmasqProcess = new QProcess(this);
    m_dnsmasqProcess->setProgram(QStringLiteral("sudo"));
    m_dnsmasqProcess->setArguments(
        {QStringLiteral("dnsmasq"), QStringLiteral("--conf-file=") + configPath});
    m_dnsmasqProcess->start();

    if (!m_dnsmasqProcess->waitForStarted(2000)) {
        qDebug().noquote() << "DynamicSplitResolver: dnsmasq failed to start:"
                          << m_dnsmasqProcess->errorString();
        delete m_dnsmasqProcess;
        m_dnsmasqProcess = nullptr;
        destroyIpset(ipsetV4Name);
        destroyIpset(ipsetV6Name);
        return false;
    }

    // dnsmasq forks briefly on startup even with --no-daemon while it
    // validates config and binds sockets; give it a moment and confirm it's
    // still alive rather than having exited immediately on a config error
    // (bad listen-address, port already in use, etc — all real
    // possibilities here since callers are responsible for picking a free
    // address/port, not this class).
    if (m_dnsmasqProcess->waitForFinished(500)) {
        qDebug().noquote() << "DynamicSplitResolver: dnsmasq exited immediately, exit code"
                          << m_dnsmasqProcess->exitCode() << "stderr:"
                          << m_dnsmasqProcess->readAllStandardError();
        delete m_dnsmasqProcess;
        m_dnsmasqProcess = nullptr;
        destroyIpset(ipsetV4Name);
        destroyIpset(ipsetV6Name);
        return false;
    }

    m_configPath = configPath;
    m_ipsetV4Name = ipsetV4Name;
    m_ipsetV6Name = ipsetV6Name;

    qDebug().noquote() << "DynamicSplitResolver: started, listening on"
                      << listenAddress.toString() << ":" << listenPort << "for"
                      << splitDomains.size() << "domain(s), ipsets" << ipsetV4Name
                      << "/" << ipsetV6Name;
    return true;
}

bool DynamicSplitResolver::stop()
{
    if (m_dnsmasqProcess) {
        if (m_dnsmasqProcess->state() != QProcess::NotRunning) {
            // dnsmasq was launched via "sudo dnsmasq ...", so the QProcess
            // handle we hold is sudo's PID, not dnsmasq's — terminate()
            // alone would only signal sudo. Kill dnsmasq itself by config
            // file identity instead, which is unambiguous since each
            // instance gets its own freshly-written config path.
            QProcess::execute(QStringLiteral("sudo"),
                              {QStringLiteral("pkill"), QStringLiteral("-f"),
                               QStringLiteral("dnsmasq --conf-file=") + m_configPath});
            m_dnsmasqProcess->waitForFinished(2000);
        }
        delete m_dnsmasqProcess;
        m_dnsmasqProcess = nullptr;
    }

    if (!m_ipsetV4Name.isEmpty()) {
        destroyIpset(m_ipsetV4Name);
        m_ipsetV4Name.clear();
    }
    if (!m_ipsetV6Name.isEmpty()) {
        destroyIpset(m_ipsetV6Name);
        m_ipsetV6Name.clear();
    }

    if (!m_configPath.isEmpty()) {
        QFile::remove(m_configPath);
        m_configPath.clear();
    }

    return true;
}
